flowable:
  databaseSchemaUpdate : true #create-drop create false
  cmmn.enabled : true
  dmn.enabled : true
  form.enabled : true
  databaseSchema : plumdo_flow

logging:
  name: flow-service
    
---

#生产环境
spring.profiles: service-pro
  
  
---

#开发环境
spring.profiles: service-dev
  
server:
  port : 8081

  